### ISSUE TITLE
can't run the container.

### ISSUE THREAD

**Issue by humanperzeus** [DCsunset/docker-i3-arch-vnc#1]
when building, no error.
but I cannot start it and connect to it would love to use this container. The same is for your other docker container, its not connecting when building manually.

**Comment by DCsunset** [comment]
Hello, could you list the command that you use to start the container?
It would also be helpful to list the error messages if any.

**Comment by DmitryKvant** [comment]
dmitrykvant@kvantbook yandexservicebotpuppeteer % docker run -d --name i3-arch-vnc -p 5900:5900 -p 6080:6080 -e VNC_PASSWD=password dcsunset/i3-arch-vnc
27638f67115ce00995169a1b653b696232225520011845e47d048d50aa1cf212
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/scripts/start.sh": stat /scripts/start.sh: no such file or directory: unknown.

**Comment by DCsunset** [comment]
Thanks for your feedback. There was a bug in the Dockerfile.
The latest version should work normally.
